{% set name = "pyfileindex" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 39bb9e2ee14af18a8d3a0587c4f9962eb1445809e96b5cb14f08c742b2909665

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pip
    - pandas >=2.0.1
    - scandir >=1.10.0

test:
  imports:
    - pyfileindex
  commands:
    - pip check

about:
  home: https://github.com/pyiron/pyfileindex
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pythonic file system index

  description: |
    The pyfileindex helps to keep track of files in a specific directory, 
    to monitor added files, modified files and deleted files. The module 
    is compatible with Python 2.7-3.7 but restricted to Unix-like system 
    - Windows is not supported.
  doc_url: https://github.com/pyiron/pyfileindex
  dev_url: https://github.com/pyiron/pyfileindex

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
