{% set name = "pyfileindex" %}
{% set version = "0.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyfileindex-{{ version }}.tar.gz
  sha256: 7a389f03794ed24ed579805d51dcb49a7a9d72ca1d1bb5fe78e719cc6ae050ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - numpy
    - pandas
    - scandir
  run:
    - numpy >=1.23.5,<=1.26.0
    - python >=3.8
    - pandas >=1.5.3,<=2.1.3
    - scandir ==1.10.0

test:
  imports:
    - pyfileindex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyfileindex/pyfileindex
  summary: pyfileindex - pythonic file system index
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
