{% set name = "pyfileindex" %}
{% set version = "0.0.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyfileindex-{{ version }}.tar.gz
  sha256: 5a711dd07e86f46eadb33427cea5f07ba50801501b076ce72c93d3fdcedd5d59

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - numpy
    - pandas
    - scandir
    - versioneer
    - toml
  run:
    - numpy >=1.23.5,<=1.26.4
    - python >=3.8
    - pandas >=1.5.3,<=2.2.2
    - scandir ==1.10.0

test:
  imports:
    - pyfileindex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyfileindex/pyfileindex
  summary: pyfileindex - pythonic file system index
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
