{% set name = "pyfileindex" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d993d0197b26d9152964da9c617e21921e47208160145a356828e192af95eb25

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - pip
    - pandas
    - scandir

test:
  imports:
    - pyfileindex
  commands:
    - pip check

about:
  home: https://github.com/pyiron/pyfileindex
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pythonic file system index

  description: |
    The pyfileindex helps to keep track of files in a specific directory, 
    to monitor added files, modified files and deleted files. The module 
    is compatible with Python 2.7-3.7 but restricted to Unix-like system 
    - Windows is not supported.
  doc_url: https://github.com/pyiron/pyfileindex
  dev_url: https://github.com/pyiron/pyfileindex

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - muh-hassani
    - niklassiemer
