{% set name = "pyfileindex" %}
{% set version = "0.0.38" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyfileindex-{{ version }}.tar.gz
  sha256: 7eb099dd99b77b261808e329fdeab8faf2aa8e132bd52ee06d054ca4b4adffe7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
    - numpy
    - pandas
    - scandir
    - toml
  run:
    - numpy >=1.23.5,<=2.2.4
    - python >={{ python_min }}
    - pandas >=1.5.3,<=2.3.1
    - scandir ==1.10.0

test:
  imports:
    - pyfileindex
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyfileindex/pyfileindex
  summary: pyfileindex - pythonic file system index
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
