{% set name = "pyfileindex" %}
{% set version = "0.0.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyfileindex-{{ version }}.tar.gz
  sha256: dde8f8d6b8e9670b4d463644285fa99e09e988bc6e2267db46e63ec3a1aeb36f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - numpy
    - pandas
    - scandir
    - versioneer
    - toml
  run:
    - numpy >=1.23.5,<=2.1.1
    - python >=3.8
    - pandas >=1.5.3,<=2.2.3
    - scandir ==1.10.0

test:
  imports:
    - pyfileindex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyfileindex/pyfileindex
  summary: pyfileindex - pythonic file system index
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
