schema_version: 1

context:
  name: pyfileindex
  version: "0.1.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyfileindex-${{ version }}.tar.gz
  sha256: 3b9f14eb9c989d55b7a2259d245d62271c40cf8773510e266681a9064f702f09

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
    - pandas
  run:
    - python >=${{ python_min }}
    - pandas >=1.5.3,<=2.3.3
tests:
  - python:
      imports:
        - pyfileindex
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: pyfileindex - pythonic file system index
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyfileindex/pyfileindex

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
