schema_version: 1

context:
  name: pyfileindex
  version: "0.2.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyfileindex-${{ version }}.tar.gz
  sha256: b2f14fb0718c80ec9b9b166954e5e0a1c84febbf67d37513ccc1e92572370dad
  patches:
    - watch.patch

build:
  number: 3
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
    - pandas
  run:
    - python >=${{ python_min }}
    - pandas >=1.5.3,<=3.0.3
tests:
  - python:
      imports:
        - pyfileindex
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: pyfileindex - pythonic file system index
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyfileindex/pyfileindex

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
