schema_version: 1

context:
  name: pyfileindex
  version: "0.2.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyfileindex-${{ version }}.tar.gz
  sha256: 73559424955763e3c675526f0113e6e00a3e06772eda7cdcfc0a09b9271f887a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
    - pandas
  run:
    - python >=${{ python_min }}
    - pandas >=1.5.3,<=3.0.6
tests:
  - python:
      imports:
        - pyfileindex
      python_version:
        - ${{ python_min }}
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: pyfileindex - pythonic file system index
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyfileindex/pyfileindex

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
