schema_version: 1

context:
  name: pyfileindex
  version: 0.0.39

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyfileindex-${{ version }}.tar.gz
  sha256: 28139524d3ab1a08bff3e3c5f8d4062a37c261f982aba091abd316e079581729

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
    - numpy
    - pandas
    - scandir
    - toml
  run:
    - numpy >=1.23.5,<=2.3.2
    - python >=${{ python_min }}
    - pandas >=1.5.3,<=2.3.1
    - scandir ==1.10.0

tests:
  - python:
      imports:
        - pyfileindex
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: pyfileindex - pythonic file system index
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyfileindex/pyfileindex

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
