travis:
  secure:
    BINSTAR_TOKEN: aWr3wrzKnSu7dK+oQay4bWtTvCGieJH5gYdFXb2fVAmR1dfvvm9gMe+Rm09iDz66e2+c1Add1gK+9jReNMEp0Il0nzDVUk4grrvxcwf6nzyk416eK6ghcBx+yG2aJ3brBC3p/AjlBZ/+8hJG5ZAwZv+3tOt+YSUxLd9MenR8XiUAhwDZoGfkRhBztRBlHcd+1YANouliaU6Trzvww+jGbL5ksHSR5riYSmaWWoxtTkH9oNKLxRUqOfXXB36VHn2Qj8Di93RZAfft+STUHcmN9pFLwYS5stoU4XZ7hQRTjK46U3XKSrGy/kommsnSIWIlCBc4qXpDxPJDyrhaEgzIysx85u5F6CnJ2Phg9/SESeBTMxpPNIY36QxevlIZeXFpNf9kdztBIFJxQm5bTfSVmuC9OatvEw1ZLUC9EQBp313ET9Kh0iAavdElS+w5zZaocQdg7CqoyMHLxTJdCV9wUz25+Rz63hSPgmyfvyAxDPyRf7O5vqV5+o4AFJNyDGoHbIZacTQPqNaIsI72XYiXh0r5GX0m1ljC5a0jGOKLtxGA0W61kijbYuG8iUr3MRHrpM+nezboC/W9BzrxqMal6B2NjPeAOAC0P6OM56ObNyw4GElIbp08aJUe9/Wfgn0a0FB8X+k07OD1mcBcFDjP0gctIScRc/fULK8sf2dHaeg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
